### ISSUE TITLE
equuleus doesn't build

### ISSUE THREAD

**Issue by dutty5** [dd010101/vyos-build#3]
Hi, thank you for your effort to fork the original vyos-buld repository.

Is it a work a progress, or am I missing something?

I cannot build the equuleus. The script still depends on (now access restricted) vyos_mirror and local.deb.vyos.io repos.

I start the build as usual:
`docker pull vyos/vyos-build:equuleus`
`git clone -b equuleus --single-branch https://github.com/dd010101/vyos-build`
`cd vyos-build/`
`docker run --rm -it --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:equuleus bash`
`./configure --architecture amd64 --build-by "j.randomhacker@vyos.io"`
`sudo make iso`

and get
`Err:10 https://equuleus-packages.vyos.net equuleus InRelease
  403  Forbidden [IP: 104.18.30.79 443]`
  `Err:40 http://local.deb.vyos.io/extended-lts buster InRelease
  Could not connect to local.deb.vyos.io:80 (10.217.40.152), connection timed out`

May be I use this repo incorrectly.
Also, branding removal is mentioned in this repo, however there is no instructions how to use it.
Some short manual here how to use this repo to build the iso properly is much appreciated.

**Comment by dd010101** [comment]
Hi, this repository is just companion for [vyos-jenkins](https://github.com/dd010101/vyos-jenkins).
You need to build package repository on your own and that's what the vyos-jenkins repository is for.

This repository has only neccesary changes to allow us to build all packages via official Jenkins build scripts. It won't work on its own. 

There is no way to build packages the old way unless you have your own or other unofficial package repository as replacement for the closed repository. Then you can use the usual build ISO method with few extra parameters, see vyos-jenkins for details. There you will also see the instructions how to remove branding.

**Comment by dutty5** [comment]
Ah, that is good to know...

Thank you
